apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app1-vs
  namespace: app1
spec:
  hosts:
  - "app1.app1"
  http:
  - match:
    - headers:
        PreviewVersion:
          exact: "yes"
    route:
    - destination:
        host: app1-new
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: app1
        port:
          number: 80

