apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app1
  name: app1
  namespace: app1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: app1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app1
  name: app1-new
  namespace: app1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: app1
  sessionAffinity: None
  type: ClusterIP
